clear;
close all;
clc;

datasets = ["AEEEM", "RELINK", "SOFTLAB", "NASA"];

alpha = 0.005;

outputRoot = fullfile(pwd, 'outlier_plots');

if ~exist(outputRoot,'dir')
    mkdir(outputRoot);
end

datasetNames       = strings(0,1);
projectNames       = strings(0,1);

totalInstances     = [];
totalFeatures      = [];

defectCounts       = [];
defectPercentages  = [];

thresholds         = [];

outlierCounts      = [];
outlierPercentages = [];

for dd = 1:numel(datasets)

    dataset = datasets(dd);

    fprintf('\n\n');
    fprintf('====================================================\n');
    fprintf('DATASET: %s\n', dataset);
    fprintf('====================================================\n');

    dataFolder = fullfile('data', char(dataset));

    files = dir(fullfile(dataFolder, '*.xlsx'));

    if isempty(files)

        warning('No XLSX files found for dataset: %s', dataset);
        continue;

    end

    [~, idx] = sort({files.name});
    files = files(idx);

    nProj = numel(files);

    fprintf('Number of projects: %d\n', nProj);

    outputFolder = fullfile(outputRoot, char(dataset));

    if ~exist(outputFolder,'dir')
        mkdir(outputFolder);
    end

    for i = 1:nProj

        filename = fullfile( ...
            files(i).folder, ...
            files(i).name);

        T = readmatrix(filename);

        X = T(:,1:end-1);
        Y = T(:,end);

        [~, projectName, ~] = ...
            fileparts(files(i).name);

        fprintf('\n--------------------------------------------\n');
        fprintf('Dataset : %s\n', dataset);
        fprintf('Project : %s\n', projectName);

        validRows = ...
            all(isfinite(X),2) & ...
            isfinite(Y);

        X = X(validRows,:);
        Y = Y(validRows);

        featureStd = std(X,0,1);

        validFeatures = featureStd > 0;

        X = X(:,validFeatures);

        [nSamples, nFeatures] = size(X);

        nDefects = sum(Y == 1);

        defectPercentage = ...
            100 * nDefects / nSamples;

        fprintf('Samples       : %d\n', nSamples);
        fprintf('Features      : %d\n', nFeatures);

        fprintf( ...
            'Defects        : %d (%.2f%%)\n', ...
            nDefects, ...
            defectPercentage);

        fprintf( ...
            'Non-defects    : %d (%.2f%%)\n', ...
            sum(Y == 0), ...
            100 * sum(Y == 0) / nSamples);

        if nSamples <= nFeatures

            warning( ...
                ['%s/%s: samples (%d) <= features (%d). ', ...
                 'Classical Mahalanobis distance may be unstable.'], ...
                 dataset, ...
                 projectName, ...
                 nSamples, ...
                 nFeatures);

        end

        Z = normalize(X, 'zscore');

        md2 = mahal(Z, Z);

        threshold = ...
            chi2inv(1-alpha, nFeatures);

        isOutlier = ...
            md2 > threshold;

        nOutliers = ...
            sum(isOutlier);

        outlierPercentage = ...
            100 * nOutliers / nSamples;

        fprintf('\nOVERALL OUTLIER DETECTION\n');

        fprintf( ...
            'MD threshold   : %.4f\n', ...
            threshold);

        fprintf( ...
            'Outliers       : %d / %d (%.2f%%)\n', ...
            nOutliers, ...
            nSamples, ...
            outlierPercentage);

        datasetNames(end+1,1) = dataset;

        projectNames(end+1,1) = ...
            string(projectName);

        totalInstances(end+1,1) = ...
            nSamples;

        totalFeatures(end+1,1) = ...
            nFeatures;

        defectCounts(end+1,1) = ...
            nDefects;

        defectPercentages(end+1,1) = ...
            defectPercentage;

        thresholds(end+1,1) = ...
            threshold;

        outlierCounts(end+1,1) = ...
            nOutliers;

        outlierPercentages(end+1,1) = ...
            outlierPercentage;

        fig = figure( ...
            'Units','inches', ...
            'Position',[1 1 8.5 5.5], ...
            'PaperPositionMode','auto', ...
            'Color','w', ...
            'InvertHardcopy','off');

        ax = axes( ...
            fig, ...
            'Units','normalized', ...
            'Position',[0.11 0.14 0.84 0.80], ...
            'Color','w', ...
            'XColor','k', ...
            'YColor','k');

        hold(ax,'on');

        instanceIndex = ...
            (1:nSamples)';

        h1 = scatter( ...
            ax, ...
            instanceIndex(~isOutlier), ...
            md2(~isOutlier), ...
            45, ...
            'o', ...
            'filled');

        h2 = scatter( ...
            ax, ...
            instanceIndex(isOutlier), ...
            md2(isOutlier), ...
            85, ...
            'x', ...
            'LineWidth',2);

        h3 = yline( ...
            ax, ...
            threshold, ...
            '--', ...
            'Color','k', ...
            'LineWidth',2);

        xlabel( ...
            ax, ...
            'Instance Index', ...
            'FontSize',16, ...
            'FontWeight','bold', ...
            'Color','k');

        ylabel( ...
            ax, ...
            'Squared Mahalanobis Distance', ...
            'FontSize',16, ...
            'FontWeight','bold', ...
            'Color','k');

        ax.FontSize = 14;

        ax.FontWeight = ...
            'normal';

        ax.LineWidth = ...
            1.2;

        ax.Color = ...
            'w';

        ax.XColor = ...
            'k';

        ax.YColor = ...
            'k';

        ax.GridColor = ...
            'k';

        ax.GridAlpha = ...
            0.15;

        grid(ax,'on');
        box(ax,'on');

        lgd = legend( ...
            ax, ...
            [h1 h2 h3], ...
            { ...
                'Normal Instance', ...
                'Outlier', ...
                'Outlier Threshold' ...
            }, ...
            'Location','northeast', ...
            'FontSize',12, ...
            'Box','on');

        lgd.Color = ...
            'w';

        lgd.TextColor = ...
            'k';

        lgd.EdgeColor = ...
            'k';

        lgd.AutoUpdate = ...
            'off';

        drawnow;

        pngFile = fullfile( ...
            outputFolder, ...
            [projectName ...
            '_mahalanobis_outliers.png']);

        exportgraphics( ...
            fig, ...
            pngFile, ...
            'Resolution',300, ...
            'BackgroundColor','white');

        epsFile = fullfile( ...
            outputFolder, ...
            [projectName ...
            '_mahalanobis_outliers.eps']);

        exportgraphics( ...
            fig, ...
            epsFile, ...
            'ContentType','vector', ...
            'BackgroundColor','white');

        figFile = fullfile( ...
            outputFolder, ...
            [projectName ...
            '_mahalanobis_outliers.fig']);

        savefig( ...
            fig, ...
            figFile);

        fprintf( ...
            '\nSaved PNG: %s\n', ...
            pngFile);

        fprintf( ...
            'Saved EPS: %s\n', ...
            epsFile);

        fprintf( ...
            'Saved FIG: %s\n', ...
            figFile);

        close(fig);

    end

end

OutlierSummary = table( ...
    datasetNames, ...
    projectNames, ...
    totalInstances, ...
    totalFeatures, ...
    defectCounts, ...
    defectPercentages, ...
    thresholds, ...
    outlierCounts, ...
    outlierPercentages, ...
    'VariableNames',{ ...
        'Dataset', ...
        'Project', ...
        'Samples', ...
        'Features', ...
        'Defect_Count', ...
        'Defect_Percentage', ...
        'MD_Threshold', ...
        'Outlier_Count', ...
        'Outlier_Percentage'});

fprintf('\n\n');

disp('========================================================');
disp('              MAHALANOBIS OUTLIER SUMMARY');
disp('========================================================');

disp(OutlierSummary);

csvFile = fullfile( ...
    outputRoot, ...
    'mahalanobis_outlier_summary_all_datasets.csv');

writetable( ...
    OutlierSummary, ...
    csvFile);

fprintf('\nCombined summary written to:\n');
fprintf('%s\n', csvFile);

nRows = height(OutlierSummary);

defectFormatted = strings(nRows,1);
outlierFormatted = strings(nRows,1);

for i = 1:nRows

    defectFormatted(i) = sprintf( ...
        '%d (%.2f%%)', ...
        OutlierSummary.Defect_Count(i), ...
        OutlierSummary.Defect_Percentage(i));

    outlierFormatted(i) = sprintf( ...
        '%d (%.2f%%)', ...
        OutlierSummary.Outlier_Count(i), ...
        OutlierSummary.Outlier_Percentage(i));

end

PaperSummary = table( ...
    OutlierSummary.Dataset, ...
    OutlierSummary.Project, ...
    OutlierSummary.Samples, ...
    OutlierSummary.Features, ...
    defectFormatted, ...
    outlierFormatted, ...
    'VariableNames',{ ...
        'Dataset', ...
        'Project', ...
        'Samples', ...
        'Features', ...
        'Defects_n_Percent', ...
        'Outliers_n_Percent'});

fprintf('\n\n');

disp('========================================================');
disp('                  PAPER SUMMARY');
disp('========================================================');

disp(PaperSummary);

paperCsvFile = fullfile( ...
    outputRoot, ...
    'mahalanobis_outlier_summary_paper.csv');

writetable( ...
    PaperSummary, ...
    paperCsvFile);

fprintf('\nPaper-formatted summary written to:\n');
fprintf('%s\n', paperCsvFile);
